-- MySQL Script generated by MySQL Workbench
-- Thu Jul  1 20:44:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agendame
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agendame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agendame` DEFAULT CHARACTER SET utf8mb4 ;
USE `agendame` ;

-- -----------------------------------------------------
-- Table `agendame`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendame`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombes` VARCHAR(40) NULL DEFAULT NULL,
  `apellidos` VARCHAR(50) NULL DEFAULT NULL,
  `fechanac` DATE NULL DEFAULT NULL,
  `ocupacion` CHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  `clave` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `agendame`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agendame`.`eventos` (
  `idevento` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `hora` CHAR(10) NULL DEFAULT NULL,
  `fecha_hora` DATETIME NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `lugar` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`idevento`),
  INDEX `idusuario` (`idusuario` ASC),
  CONSTRAINT `eventos_ibfk_1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `agendame`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 202
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
